# Generated by Django 5.2.13 on 2026-05-03 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_evt', models.CharField(choices=[('COURS', 'Cours'), ('REUNION', 'Réunion'), ('EXAMEN', 'Examen'), ('PERSONNEL', 'Personnel'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('lieu', models.CharField(blank=True, default='', max_length=200)),
                ('priorite', models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='MOYENNE', max_length=10)),
                ('est_prive', models.BooleanField(default=False)),
                ('couleur', models.CharField(default='#3b82f6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='evenements_participes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
