# Generated by Django 5.2.13 on 2026-05-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={},
        ),
        migrations.RenameField(
            model_name='groupe',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='message',
        ),
        migrations.AlterField(
            model_name='groupe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
