# Generated by Django 5.2.13 on 2026-05-03 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('INVITATION', 'Invitation reçue'), ('ACCEPTATION', 'Invitation acceptée'), ('PARTAGE', 'Événement partagé'), ('RAPPEL', 'Rappel événement'), ('INFO', 'Information')], default='INFO', max_length=15)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, default='', max_length=300)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
